### ISSUE TITLE
Automatic calculation of the effective dimension of a source

### ISSUE THREAD

**Issue by lucarebuffi** [oasys-kit/ShadowOui#106]
Internally use an empty element positioned outside the physical source, with a retrace up to the center of the source

**Comment by srio** [comment]
Is it very important to have it "automatic"?

Other posible options: 

1) place a screen at X meters and then Plotxy with retrace=-X
2) place a clone of the beloved "Ideal Lens" (you know...), that focus in 1:1 without aberrations, for example an ellipsoidal mirror at 45 deg. 

In fact, the "retrace" used in plotxy should do the job: I think (to be checked), that placing retrace to "image plane new position"=0.0, the rays are projected to the plane y=0, and the result should be identical to propagate to a given distance and then backpropagate to the source center. 

Let me know what you think...

**Comment by lucarebuffi** [comment]
It is not important, but useful. 

The first option (empty element + plotxy retraced) you mentioned is the way I usually do. I found that is not immediate for basic users. 
The real dimension of the source is an important information (for example we use it as a check when comparing Shadow source simulation with Spectra source simulation), and it could be useful to have suc a plot available with the others as well.

**Comment by lucarebuffi** [comment]
It can be available clicking a button and showing the result in a popup window, in order to not overload the CPU during normal calculation

**Comment by lucarebuffi** [comment]
Done as an option.
