### ISSUE TITLE
BM error message if Emin=Emax

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#125]
In fact, BM also allows a monochromatic source if Emin=Emax, that should be permitted. 

(No urgence!!)

**Comment by lucarebuffi** [comment]
Is it true also for Wiggler, Undulator and Geometrical Source?
Is it true also for XOPPY Sources?

**Comment by lucarebuffi** [comment]
A comment: The result with Emin=Emax looks inconsitent.

To check it, modify ow_bending_magnet.py:

from:         

        congruence.checkLessThan(self.e_min, self.e_max,  "Minimum energy",  "Maximum energy")

to:

        congruence.checkLessOrEqualThan(self.e_min, self.e_max,  "Minimum energy",  "Maximum energy")

**Comment by srio** [comment]
Let me think, do not change anything write now.

**Comment by lucarebuffi** [comment]
Sure I don't....I will be fixing only clamorous bugs before the workshop...

**Comment by srio** [comment]
Good. I really do not know is the Emin=Emax works in all cases. 
I think it is not the moment to check. We can always suggest to make a very small interval is one wants monochronatic. 
For the new sources to be written in python I will make sure that this work

**Comment by lucarebuffi** [comment]
Yep!
