### ISSUE TITLE
Zone plate

### ISSUE THREAD

**Issue by RubenReininger** [oasys-kit/ShadowOui#177]
Gents,
There seems to be a bug with the zone plate ray tracings. The calculation of the zone plate parameters are OK but the ray tracing is not.

Please see attached file.

Best regards to both.

Ruben

[zone plate.ows.zip](https://github.com/lucarebuffi/ShadowOui/files/1195412/zone.plate.ows.zip)

**Comment by lucarebuffi** [comment]
Fixed in Version 1.4.53
