### ISSUE TITLE
Crash: Bad internal unit KIND

### ISSUE THREAD

**Issue by djvine** [oasys-kit/ShadowOui#186]
Hello,
Downloaded Shadow Oui for the first time today and it crashes crashes sometime when I add optical elements, sometimes when I start a simulation run.

I'm using Debian stretch and I set up a basic simulation: geometric source,  zone plate and plot. The terminal output is below:

[david@dawn oasys]$ ./start_oasys.sh 
Activating configuration for <class 'oasys.canvas.conf.oasysconf'>
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at 0x7f6b95b7b798>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Time from last update 0:59:11.693530 (1519576709.9875)
Got pypi packages: [Installable(name='OASYS1-WISE', version='1.1.3', summary='WISE in Python', description='WISE in OASYS - Prototype Version', package_url='http://pypi.python.org/pypi/OASYS1-WISE', release_urls=[ReleaseUrl(filename='OASYS1-WISE-1.1.3.tar.gz', url='https://pypi.python.org/packages/e9/21/2f24a6b0ac202cf539fc3d3d48d4de642095a3c6b12e55e2310d1b04c6ed/OASYS1-WISE-1.1.3.tar.gz', size=294050, python_version='source', package_type='sdist')]), Installable(name='OASYS1-XRayServer', version='1.0.19', summary="X-Ray Server: Sergey Stepanov's X-Ray Server on OASYS", description="This is the project for XRayServer (Sergey Stepanov's X-Ray Server) under OASYS", package_url='http://pypi.python.org/pypi/OASYS1-XRayServer', release_urls=[ReleaseUrl(filename='OASYS1-XRayServer-1.0.19.tar.gz', url='https://pypi.python.org/packages/be/c8/9461785c402ac3026d63ce20799508313e352c9610b6692671007550adfa/OASYS1-XRayServer-1.0.19.tar.gz', size=108780, python_version='source', package_type='sdist')]), Installable(name='OASYS1-XOPPY', version='1.0.33', summary='XOPPY: XOP (X-ray oriented programs) in Python', description='This is the project for XOPPY (XOP under python3) under OASYS', package_url='http://pypi.python.org/pypi/OASYS1-XOPPY', release_urls=[ReleaseUrl(filename='OASYS1-XOPPY-1.0.33.tar.gz', url='https://pypi.python.org/packages/11/e8/469486ba8f708566fca7ab7be2119d23be57896ed0bfc9d3e954ff2f2fe0/OASYS1-XOPPY-1.0.33.tar.gz', size=10393642, python_version='source', package_type='sdist')]), Installable(name='OASYS1-ShadowOui', version='1.4.39', summary='Shadow, Ray-tracing simulation software', description='ShadowOui (Shadow3 Oasys User Interface) is an Oasys add-on package to be installed via the add-on manager tool.\n\nIt contains the Shadow 3 ray-tracing simulation software integrated into the Oasys environment.', package_url='http://pypi.python.org/pypi/OASYS1-ShadowOui', release_urls=[ReleaseUrl(filename='OASYS1-ShadowOui-1.4.39.tar.gz', url='https://pypi.python.org/packages/b9/f8/d957876ec2daff4a444e7f8988fa06c35c29c1ed129e662b89eb7de64577/OASYS1-ShadowOui-1.4.39.tar.gz', size=3054738, python_version='source', package_type='sdist')])]
SRW is not available
SRW is not available
Saving widget registry cache with 93 entries ('/home/david/.cache/OASYS1/1.0/registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at 0x7f6b95125948> on 'CanvasScene(objectName='', ...)'.
Modified strict check (modified flag: False, undo stack clean: True, properties: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at 0x7f6b95125948> on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at 0x7f6b743911f8>' on 'CanvasScene(objectName='', ...)'
Changing current work dir to '/home/david/Oasys'
Added node 'Geometrical Source' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f6b7440baf8>' to 'CanvasScene(objectName='', ...)'
Added node 'Zone Plate' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f6b743c1708>' to 'CanvasScene(objectName='', ...)'
Setting interaction '<orangecanvas.document.interactions.NewLinkAction object at 0x7f6b776573a8>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f6b7440baf8> is the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Geometrical Source' ('Beam') -> 'Zone Plate' ('Input Beam') to scheme 'test'.
Link added (SchemeLink((Geometrical Source, Beam) -> (Zone Plate, Input Beam))). Scheduling signal data update.
Added link 'Geometrical Source' -> 'Zone Plate' to 'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
Added node 'Plot XY' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f6b776811f8>' to 'CanvasScene(objectName='', ...)'
Setting interaction '<orangecanvas.document.interactions.NewLinkAction object at 0x7f6b7760aa68>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f6b743c1708> is the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Zone Plate' ('Beam') -> 'Plot XY' ('Input Beam') to scheme 'test'.
Link added (SchemeLink((Zone Plate, Beam) -> (Plot XY, Input Beam))). Scheduling signal data update.
Added link 'Zone Plate' -> 'Plot XY' to 'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
 Generated          250  rays out of         5000
                    500
                    750
                   1000
                   1250
                   1500
                   1750
                   2000
                   2250
                   2500
                   2750
                   3000
                   3250
                   3500
                   3750
                   4000
                   4250
                   4500
                   4750
                   5000
 Exit from SOURCE
'Geometrical Source' sending <class 'orangecontrib.shadow.util.shadow_objects.ShadowBeam'> (id: (1, 'Beam', None)) on channel 'Beam'
'UpdateRequest' event, queued signals: 1
Processing queued signals
Pending nodes: {SchemeNode(description_id=ow_zone_plate, title='Zone Plate', ...)}
Blocking nodes: set()
Nodes for update ['Zone Plate']
Processing 'Zone Plate', sending 1 signals.
 Call to RESET
 Exit from RESET
 Call to SETSOUR
 Exit from SETSOUR
 Call to IMREF
 Exit from IMREF
 Call to OPTAXIS
At line 416 of file src/fortran/stringio.f90
Internal Error: get_unit(): Bad internal unit KIND

**Comment by srio** [comment]
Hi David,

are you using zone plates? This element is "under development" and it 
may present problems (running and results). Do you have problems with 
other elements?

Regards,
Manuel

**Comment by djvine** [comment]
Hi Manuel,

thanks for the fast reply.

If i use the geometrical source and XY plot there are no problems. If i add
a slit between source and XY plot it crashes with the same error (given
below). It seems to always follow the line "Call To OPTAXIS".

[david@dawn oasys]$ ./start_oasys.sh
Activating configuration for <class 'oasys.canvas.conf.oasysconf'>
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at
0x7f56db253798>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Time from last update 2:00:09.655493 (1519576709.9875)
Got pypi packages: [Installable(name='OASYS1-WISE', version='1.1.3',
summary='WISE in Python', description='WISE in OASYS - Prototype Version',
package_url='http://pypi.python.org/pypi/OASYS1-WISE',
release_urls=[ReleaseUrl(filename='OASYS1-WISE-1.1.3.tar.gz', url='
https://pypi.python.org/packages/e9/21/2f24a6b0ac202cf539fc3d3d48d4de642095a3c6b12e55e2310d1b04c6ed/OASYS1-WISE-1.1.3.tar.gz',
size=294050, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-XRayServer', version='1.0.19', summary="X-Ray
Server: Sergey Stepanov's X-Ray Server on OASYS", description="This is the
project for XRayServer (Sergey Stepanov's X-Ray Server) under OASYS",
package_url='http://pypi.python.org/pypi/OASYS1-XRayServer',
release_urls=[ReleaseUrl(filename='OASYS1-XRayServer-1.0.19.tar.gz', url='
https://pypi.python.org/packages/be/c8/9461785c402ac3026d63ce20799508313e352c9610b6692671007550adfa/OASYS1-XRayServer-1.0.19.tar.gz',
size=108780, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-XOPPY', version='1.0.33', summary='XOPPY: XOP
(X-ray oriented programs) in Python', description='This is the project for
XOPPY (XOP under python3) under OASYS', package_url='
http://pypi.python.org/pypi/OASYS1-XOPPY',
release_urls=[ReleaseUrl(filename='OASYS1-XOPPY-1.0.33.tar.gz', url='
https://pypi.python.org/packages/11/e8/469486ba8f708566fca7ab7be2119d23be57896ed0bfc9d3e954ff2f2fe0/OASYS1-XOPPY-1.0.33.tar.gz',
size=10393642, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-ShadowOui', version='1.4.39', summary='Shadow,
Ray-tracing simulation software', description='ShadowOui (Shadow3 Oasys
User Interface) is an Oasys add-on package to be installed via the add-on
manager tool.\n\nIt contains the Shadow 3 ray-tracing simulation software
integrated into the Oasys environment.', package_url='
http://pypi.python.org/pypi/OASYS1-ShadowOui',
release_urls=[ReleaseUrl(filename='OASYS1-ShadowOui-1.4.39.tar.gz', url='
https://pypi.python.org/packages/b9/f8/d957876ec2daff4a444e7f8988fa06c35c29c1ed129e662b89eb7de64577/OASYS1-ShadowOui-1.4.39.tar.gz',
size=3054738, python_version='source', package_type='sdist')])]
SRW is not available
SRW is not available
Saving widget registry cache with 93 entries
('/home/david/.cache/OASYS1/1.0/registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at
0x7f56da7fda68> on 'CanvasScene(objectName='', ...)'.
Modified strict check (modified flag: False, undo stack clean: True,
properties: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at
0x7f56da7fda68> on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at
0x7f56b9a82318>' on 'CanvasScene(objectName='', ...)'
Changing current work dir to '/home/david/Oasys'
Added node 'Geometrical Source' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f56b9a7dca8>' to 'CanvasScene(objectName='', ...)'
Added node 'Screen-Slits' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f56b9ab1828>' to 'CanvasScene(objectName='', ...)'
Setting interaction '<orangecanvas.document.interactions.NewLinkAction
object at 0x7f56bcd42dc8>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f56b9a7dca8> is
the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Geometrical Source' ('Beam') -> 'Screen-Slits' ('Input Beam')
to scheme 'test'.
Link added (SchemeLink((Geometrical Source, Beam) -> (Screen-Slits, Input
Beam))). Scheduling signal data update.
Added link 'Geometrical Source' -> 'Screen-Slits' to
'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
Added node 'Plot XY' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f56bcd51b88>' to 'CanvasScene(objectName='', ...)'
Setting interaction '<orangecanvas.document.interactions.NewLinkAction
object at 0x7f56bcd72288>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f56b9ab1828> is
the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Screen-Slits' ('Beam') -> 'Plot XY' ('Input Beam') to scheme
'test'.
Link added (SchemeLink((Screen-Slits, Beam) -> (Plot XY, Input Beam))).
Scheduling signal data update.
Added link 'Screen-Slits' -> 'Plot XY' to 'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
 Generated          250  rays out of         5000
                    500
                    750
                   1000
                   1250
                   1500
                   1750
                   2000
                   2250
                   2500
                   2750
                   3000
                   3250
                   3500
                   3750
                   4000
                   4250
                   4500
                   4750
                   5000
 Exit from SOURCE
'Geometrical Source' sending <class
'orangecontrib.shadow.util.shadow_objects.ShadowBeam'> (id: (1, 'Beam',
None)) on channel 'Beam'
'UpdateRequest' event, queued signals: 1
Processing queued signals
Pending nodes: {SchemeNode(description_id=ow_screen_slits,
title='Screen-Slits', ...)}
Blocking nodes: set()
Nodes for update ['Screen-Slits']
Processing 'Screen-Slits', sending 1 signals.
 Call to RESET
 Exit from RESET
 Call to SETSOUR
 Exit from SETSOUR
 Call to IMREF
 Exit from IMREF
 Call to OPTAXIS
At line 416 of file src/fortran/stringio.f90
Internal Error: get_unit(): Bad internal unit KIND


David

**Comment by djvine** [comment]
In answering your original question: yes, its for other optical elements as
well.

David

**Comment by djvine** [comment]
Sure, it's attached with the terminal output showing the crash. FYI here's
the output of uname -a: Linux dawn 4.9.0-3-amd64 #1 SMP Debian
4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

Thanks!

[david@dawn oasys]$ ./start_oasys.sh
Activating configuration for <class 'oasys.canvas.conf.oasysconf'>
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at
0x7f61eb4b3798>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Time from last update 1 day, 0:26:05.755531 (1519576709.9875)
SRW is not available
Got pypi packages: [Installable(name='OASYS1-WISE', version='1.1.3',
summary='WISE in Python', description='WISE in OASYS - Prototype Version',
package_url='http://pypi.python.org/pypi/OASYS1-WISE',
release_urls=[ReleaseUrl(filename='OASYS1-WISE-1.1.3.tar.gz', url='
https://pypi.python.org/packages/e9/21/2f24a6b0ac202cf539fc3d3d48d4de642095a3c6b12e55e2310d1b04c6ed/OASYS1-WISE-1.1.3.tar.gz',
size=294050, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-XRayServer', version='1.0.19', summary="X-Ray
Server: Sergey Stepanov's X-Ray Server on OASYS", description="This is the
project for XRayServer (Sergey Stepanov's X-Ray Server) under OASYS",
package_url='http://pypi.python.org/pypi/OASYS1-XRayServer',
release_urls=[ReleaseUrl(filename='OASYS1-XRayServer-1.0.19.tar.gz', url='
https://pypi.python.org/packages/be/c8/9461785c402ac3026d63ce20799508313e352c9610b6692671007550adfa/OASYS1-XRayServer-1.0.19.tar.gz',
size=108780, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-XOPPY', version='1.0.33', summary='XOPPY: XOP
(X-ray oriented programs) in Python', description='This is the project for
XOPPY (XOP under python3) under OASYS', package_url='
http://pypi.python.org/pypi/OASYS1-XOPPY',
release_urls=[ReleaseUrl(filename='OASYS1-XOPPY-1.0.33.tar.gz', url='
https://pypi.python.org/packages/11/e8/469486ba8f708566fca7ab7be2119d23be57896ed0bfc9d3e954ff2f2fe0/OASYS1-XOPPY-1.0.33.tar.gz',
size=10393642, python_version='source', package_type='sdist')]),
Installable(name='OASYS1-ShadowOui', version='1.4.39', summary='Shadow,
Ray-tracing simulation software', description='ShadowOui (Shadow3 Oasys
User Interface) is an Oasys add-on package to be installed via the add-on
manager tool.\n\nIt contains the Shadow 3 ray-tracing simulation software
integrated into the Oasys environment.', package_url='
http://pypi.python.org/pypi/OASYS1-ShadowOui',
release_urls=[ReleaseUrl(filename='OASYS1-ShadowOui-1.4.39.tar.gz', url='
https://pypi.python.org/packages/b9/f8/d957876ec2daff4a444e7f8988fa06c35c29c1ed129e662b89eb7de64577/OASYS1-ShadowOui-1.4.39.tar.gz',
size=3054738, python_version='source', package_type='sdist')])]
SRW is not available
Saving widget registry cache with 93 entries
('/home/david/.cache/OASYS1/1.0/registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at
0x7f61eaa5da68> on 'CanvasScene(objectName='', ...)'.
Modified strict check (modified flag: False, undo stack clean: True,
properties: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry '<orangecanvas.registry.qt.QtWidgetRegistry object at
0x7f61eaa5da68> on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at
0x7f61c4ede5e8>' on 'CanvasScene(objectName='', ...)'
Changing current work dir to '/home/david/Oasys'
Added node 'Geometrical Source' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f61c4eddd38>' to 'CanvasScene(objectName='', ...)'
Added node 'Screen-Slits' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f61c8180af8>' to 'CanvasScene(objectName='', ...)'
Added node 'Plot XY' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f61c81a71f8>' to 'CanvasScene(objectName='', ...)'
Added node 'Plot XY (1)' to scheme 'test'.
Added item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f61c8136f78>' to 'CanvasScene(objectName='', ...)'
Removed node 'Plot XY (1)' from scheme 'test'.
Node 'Plot XY (1)' removed. Removing pending signals.
Removed item '<orangecanvas.canvas.items.nodeitem.NodeItem object at
0x7f61c8136f78>' from 'CanvasScene(objectName='', ...)'
Setting interaction '<orangecanvas.document.interactions.NewLinkAction
object at 0x7f61c813f828>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f61c8180af8> is
the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Geometrical Source' ('Beam') -> 'Screen-Slits' ('Input Beam')
to scheme 'test'.
Link added (SchemeLink((Geometrical Source, Beam) -> (Screen-Slits, Input
Beam))). Scheduling signal data update.
Added link 'Geometrical Source' -> 'Screen-Slits' to
'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
Setting interaction '<orangecanvas.document.interactions.NewLinkAction
object at 0x7f61c813fca8>' to 'CanvasScene(objectName='', ...)'
<orangecanvas.canvas.items.nodeitem.NodeItem object at 0x7f61c81a71f8> is
the new target.
proposed (weighted) links: [('Beam', 'Input Beam', 24)]
Added link 'Screen-Slits' ('Beam') -> 'Plot XY' ('Input Beam') to scheme
'test'.
Link added (SchemeLink((Screen-Slits, Beam) -> (Plot XY, Input Beam))).
Scheduling signal data update.
Added link 'Screen-Slits' -> 'Plot XY' to 'CanvasScene(objectName='', ...)'
Setting interaction 'None' to 'CanvasScene(objectName='', ...)'
'UpdateRequest' event, queued signals: 0
Pending nodes: set()
Blocking nodes: set()
Could not serialize to a literal string
Traceback (most recent call last):
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 923, in dumps
    return (literal_dumps(obj, prettyprint=prettyprint, indent=1),
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 995, in literal_dumps
    check(obj)
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 990, in check
    return all(map(check, chain(obj.keys(), obj.values())))
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 993, in check
    "literal".format(type(obj)))
TypeError: <class 'PyQt5.QtCore.QByteArray'> can not be serialized as a
python literal
Using pickle fallback
Could not serialize to a literal string
Traceback (most recent call last):
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 923, in dumps
    return (literal_dumps(obj, prettyprint=prettyprint, indent=1),
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 995, in literal_dumps
    check(obj)
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 990, in check
    return all(map(check, chain(obj.keys(), obj.values())))
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 993, in check
    "literal".format(type(obj)))
TypeError: <class 'PyQt5.QtCore.QByteArray'> can not be serialized as a
python literal
Using pickle fallback
Could not serialize to a literal string
Traceback (most recent call last):
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 923, in dumps
    return (literal_dumps(obj, prettyprint=prettyprint, indent=1),
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 995, in literal_dumps
    check(obj)
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 990, in check
    return all(map(check, chain(obj.keys(), obj.values())))
  File
"/opt/miniconda3/lib/python3.6/site-packages/orangecanvas/scheme/readwrite.py",
line 993, in check
    "literal".format(type(obj)))
TypeError: <class 'PyQt5.QtCore.QByteArray'> can not be serialized as a
python literal
Using pickle fallback
 Generated          250  rays out of         5000
                    500
                    750
                   1000
                   1250
                   1500
                   1750
                   2000
                   2250
                   2500
                   2750
                   3000
                   3250
                   3500
                   3750
                   4000
                   4250
                   4500
                   4750
                   5000
 Exit from SOURCE
'Geometrical Source' sending <class
'orangecontrib.shadow.util.shadow_objects.ShadowBeam'> (id: (1, 'Beam',
None)) on channel 'Beam'
'UpdateRequest' event, queued signals: 1
Processing queued signals
Pending nodes: {SchemeNode(description_id=ow_screen_slits,
title='Screen-Slits', ...)}
Blocking nodes: set()
Nodes for update ['Screen-Slits']
Processing 'Screen-Slits', sending 1 signals.
 Call to RESET
 Exit from RESET
 Call to SETSOUR
 Exit from SETSOUR
 Call to IMREF
 Exit from IMREF
 Call to OPTAXIS
At line 416 of file src/fortran/stringio.f90



David

**Comment by srio** [comment]
Thanks David for the workspace.

I have tested your workspace and works well in both my Mac and my Ubuntu-16.04

I suggest you reinstall shadow3 from github. 
For that, using the python for oasys (your miniconda or whatever)

python -m pip uninstall shadow3

Then download shadow3 from github, put it wherever you want (I suggest under the OASYS1 directory) , build and install locally: 

git clone https://github.com/srio/shadow3
cd shadow3
python setup.py build
python -m pip install -e . --no-deps --no-binary :all:

And restart OASYS. I hope this will solve the problem. 

Pelase let me know

**Comment by SergioLordano** [comment]
Hello Manuel,

I am facing the same issue, so I also tried the solution above. It doesn't seem a problem of specific workspaces, but something more general, since I can't run any optical element.

After I reinstalled shadow from source, an version conflict arised when loading Oasys:

``Error loading a 'oasys.menus' entry point.``
``Traceback (most recent call last):``
  ``File "/home/ABTLUS/humberto.junior/miniconda3/lib/python3.6/site-packages/oasys/canvas/conf.py", line 99, in omenus``
    ``menu = ep.load()``
 `` File "/home/ABTLUS/humberto.junior/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2301, in load``
    ``self.require(*args, **kwargs)``
 `` File "/home/ABTLUS/humberto.junior/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in require``
    ``items = working_set.resolve(reqs, env, installer, extras=self.extras)``
 ``File "/home/ABTLUS/humberto.junior/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve``
    ``raise VersionConflict(dist, req).with_context(dependent_req)``
``pkg_resources.VersionConflict: (shadow3 18.1.24 (/home/ABTLUS/humberto.junior/OASYS_ENV/shadow3), Requirement.parse('shadow3==17.3.29'))``

I guess the requirement of 'shadow3==17.3.29' is imposed by ShadowOui setup.py, so I also had to install ShadowOui from source changing the version in setup.py, line 45, to 'shadow3==18.1.24'. (for some reason it could not load wofryshadow after that and I also installed if from source without errors). 

After this, Oasys loads fine without errors, but I still get the same error when running optical elements:

`At line 416 of file src/fortran/stringio.f90`
`Internal Error: get_unit(): Bad internal unit KIND` 

Thank's for helping!

**Comment by maurov** [comment]
Hello,

I pop in this issue because I have seen this error in `stringio.f90` many times and I do not know exactly from where it comes from. I have observed that this error is not present when installing `shadow3` via `pip` but only when building it from source.

In order to check if the error is present, I have created a specific test [here](https://github.com/maurov/xraysloth/blob/master/sloth/raytracing/test/test_shadow.py) called `run_test_sbca_si555()`.

I hope it could help in the debug.

Mauro

PS: Even more weird, this test does different ray-tracing results, depending on the `shadow3` installation, but this is another story and I will report it at a certain point...

**Comment by SergioLordano** [comment]
Thank you Manuel and Mauro, the binary solved the problem here!

**Comment by srio** [comment]
Problem relates to old compiler versions. Have a look at: 

https://github.com/oasys-kit/shadow3/issues/33

**Comment by lucarebuffi** [comment]
Note: Zone Plate has been fixed with ShadowOui 1.4.53
