### ISSUE TITLE
Bug in Fortran during ShadowOui execution

### ISSUE THREAD

**Issue by SergioLordano** [oasys-kit/ShadowOui#187]
In a clean installation of Ubuntu 16.04.9 LTS, I am trying to install OASYS-1. I follow the wiki steps, it installs correctly, but a Fortran error arises in shadow3 (within ShadowOui) when any optical element is executed (the source elements run without errors).

``
At line 416 of file src/fortran/stringio.f90
``
``
Internal Error: get_unit(): Bad internal unit KIND
``

The same happens for shadow_bind_f.f90 :
``
At line 45 of file src/fortran/shadow_bind_f.f90
``

The error seems to be in shadow, so I tryied to compile it from source, out of miniconda3 installation, and it runs perfectly! So it seems to me that the problem is only in shadow3 within ShadowOui. However, I can not find the shadow3 installation that ShadowOui uses. Maybe if you can tell me this, I can try to recompile it from source using miniconda. 

the gcc and gfortran versions are 5.4.0. I also tryied to downgrade to 4.7 after running `./prepare_installation.sh` but before `./install_oasys.sh`, but did not work as well. I also reinstalled Ubuntu 16 from scratch and have the same error, even though we have other machines with Ubuntu 16 running Oasys.

Thank you so much to all Shadow/Oasys maintainers,

Sergio Lordano.

**Comment by SergioLordano** [comment]
Sorry, somehow I overlooked the very recent issue #186.

**Comment by srio** [comment]
Hi,
I tried to upload to pypi my binary wheel, but, I do not know why, it says: 
error: Upload failed (400): Binary wheel 'shadow3-18.1.24-cp36-cp36m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'.

If someone knows how to solve this, please tell me. 

In the meantime you can download the whl file from:

http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/

and then 
pip install shadow3-18.1.24-cp36-cp36m-linux_x86_64.whl

Let us know if the problem is fixed. 
Sorry for all this!
Manuel

**Comment by SergioLordano** [comment]
Hi Manuel,
This solved the problem for me! 
However, it may be useful to report that this problem appeared only when running shadow under Oasys (in my case, in miniconda python). When I installed shadow from source in /usr/bin it ran without errors in command line or with python scripts.    
Thank you so much for all the help! 
Sergio

**Comment by lucarebuffi** [comment]
Guys, you all are amazing! This is the level of collaboration we were dreaming of at the beginning of the OASYS project. Thank you very much and greetings from Berkeley!

**Comment by maurov** [comment]
@srio, in my environment (conda/python3.5) the best solution is to pip-install the shadow3 wheel from the ESRF site. I report my current workflow that seems giving the best results:

```
#create conda environment plus install base packages
conda create --name py35 python=3.5
conda activate py35
conda install --yes -c defaults pyqt=5 qt
conda install --yes numpy scipy matplotlib pyparsing pytz python-dateutil h5py
#xraylib from conda-forge
conda install --yes -c conda-forge xraylib
#pip-install PyMca&friends
pip install fisx PyMca5 silx fabio hdf5plugin
#shadow3 from ESRF wheel
wget http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.1.24-cp35-cp35m-linux_x86_64.whl
pip install shadow3-18.1.24-cp35-cp35m-linux_x86_64.whl
#pip-install OASYS base
pip install oasys-canvas-core oasys-widget-core oasys1 srxraylib syned wofry
#wofryshadow from source
git clone https://github.com/srio/wofryshadow
cd wofryshadow
pip install -e . --no-deps --no-binary :all:
cd ..
#shadowOui from source
git clone https://github.com/lucarebuffi/shadowOui
cd shadowOui
pip install -e . --no-deps --no-binary :all:
python setup.py develop
#run oasys (the add-ons should be there and working!)
python -m oasys.canvas -l4 --force-discovery
```
I hope this could help,
M.

**Comment by lucarebuffi** [comment]
type ~/miniconda3/bin/python3 -m pip install shadow3 —upgrade

**Comment by lucarebuffi** [comment]
you should have at least shadow3 18.4.11

**Comment by oatlife** [comment]
Re: lucarebuffi,

Thanks for the comment. yours is right, but upgrade doesn't work so i instead type
_python3 -m pip uninstall shadow3
python3 -m pip install shadow3_
Previously i did type "pip install shadow3" without "python3 -m...", the problem could not be resolved

**Comment by srio** [comment]
we have updated things these days. Could you tray again 
1) be sure you are using the right python 
which python3 
should point to your conda environment
2) 
python3 -m pip uninstall shadow3
python3 -m pip install shadow3

3) It it fails try: 
python3 -m pip uninstall shadow3
python3 -m pip install shadow3 http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.4.11-cp36-cp36m-linux_x86_64.whl

Let us know it it works...

**Comment by oatlife** [comment]
to install this one work well

python3 -m pip install http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/shadow3-18.4.11-cp36-cp36m-linux_x86_64.whl
