### ISSUE TITLE
Temperature factor in XOPPY or SHADOWOUI

### ISSUE THREAD

**Issue by gwax09** [oasys-kit/ShadowOui#188]
In XOP, the temperature factor can be calculated by the program. 
However, the feature is not available for XOPPY or SHADOWOUI, which asks a temperature factor to be filled.
I was wondering if you could add this feature in the future version  of XOPPY or SHADOWOUI.

**Comment by srio** [comment]
in fact it is there:
https://github.com/oasys-kit/XOPPY/issues/46
I close this one.
