### ISSUE TITLE
Can Merge Shadow Beams utility be updated automatically?

### ISSUE THREAD

**Issue by maurov** [oasys-kit/ShadowOui#190]
@lucarebuffi would be possible to include an "Automatic Execution" check box in the "Merge Shadow Beams" utility? Or is there already a way to get the "Merge Beams and Send" action run automatically if there is a beam trace in a connected optical element?

Thanks for your help

**Comment by lucarebuffi** [comment]
Sorry for answering that late. In principle any widget is not aware of how many widgets are inputting data. At the beginning it was like that, but this operation cannot be done consistently and the resulting behaviour was more upsetting than useful. I will think about doing this operation in a decent way, anyway
