### ISSUE TITLE
Undulator radiation-XOPPY

### ISSUE THREAD

**Issue by gwax09** [oasys-kit/ShadowOui#192]
When use the undulator radiation widget in XOPPY, is the calculated quantity  flux distribution (ph/s/0.1%b.w.) or flux density (ph/s/0.1%b.w./mm^2)?
And when I try to save the ascii data, the data have both rows and columns start frm 0-98 instead of the real aperture size.
Is it possible to save the data with true aperture size?

**Comment by srio** [comment]
Hello, 
The units depend on the tab: The "Undulator Flux vs E,X,Y"  the units are: ph/s/0.1%b.w./mm^2 
Integrating in E you get the "Undulator power density vs X,Y" (units are W/mm2)
Integrating in X,Y you get "Undulator Flux vs E" or "Undulator Spectral Power vs E". 

Regarding the output files, I checked that the ASCII output does not contain the X,Y values but just the pixel indices. This is managed by the silx library. You can export to other formats like HDF5 (NXDATA) and everything is saved. Additionally (see in the output tab) the application writes the file ~/Oasys/undulator_radiation.spec which contains in ASCII format most of the information of the run. They are arranged in blocks. Search for #S to see the beginning of each block.
