### ISSUE TITLE
bending magnet: bug with user units

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#194]
There is a bug in the workspace units in https://github.com/oasys-kit/ShadowOui/blob/master/orangecontrib/shadow/widgets/sources/ow_bending_magnet.py. It says: 

```
        shadow_src.src.R_MAGNET = self.magnetic_radius
        shadow_src.src.R_ALADDIN = self.magnetic_radius * 100
```
It SHOULD say: 
```
        shadow_src.src.R_MAGNET = self.magnetic_radius
        shadow_src.src.R_ALADDIN = self.magnetic_radius / self.workspace_units_to_m
```

Just for info (from https://github.com/oasys-kit/shadow3/blob/master/docs/source.nml):

```
 r_aladdin	=  0.0000000000000000E+00 - for fdistr=4,6 or f_wiggler=1;
					    bending magnet radius in units
					    of length used for source
					    size, CCW rings negative.
 r_magnet	=  0.0000000000000000E+00 - for fdistr=4,6 or f_wiggler=1;
					    bending magnet radius (m).
```

On 06.12.2018 22:24, Howard Padmore wrote:
> Hi Manolo, I will send you a ppt with some comments later, but I think
> there is a bug in the bend magnet source of OUI.  I am using v1.1 but
> its in 1.0 as well.
> 
> In the bend source itself, you can plot x-z, x'-z' etc.
> 
> I was looking at the focusing of a toroid for various reasons, with a
> small post ALSU source.  I noticed that the image was elongated with a
> coma like tail in x.  The system is set up with 0 deg rotation, ie.
> with the mirror vertically deflecting...........so because of the
> symmetry there should be no asymmetry in the image in x.  At 1st I
> thought that the mirror was rotated to be horizontally deflecting, but
> no, the rotation angle is zero.
> 
> So I went to the bend source itself.  In the source icon you can look
> at any cut in phase space.  Looking at x-z, the source has the same
> horizontal coma tail.   If you look in x-x', you see a correlation in
> these parameters.........x-x' map out a parabola.   
> 
> In fact they should, because as the beam sweeps around the bend magnet
> in the horizontal plane, the intercept of the ray with the center of
> the source is finite.  Its easy to show that for a bend radius R and
> an angle theta, the position axis point should be R (theta^2) / 2.  
> So for my case, R = 5 m, theta = 1e-3 rads, and so the maximum point
> in the position axis should be 2.5 microns.   As you have the theta^2
> term, the image you get projected to the center of the bend magnet is
> coma like.....and should have a distinct maximum of +2.5 microns.  In
> OUI this maximum is 250 microns.It isn't a unites error...........I
> always work in meters and the source units are anyway in meters.  Same
> for exact and pre-computed.  If I reduce the aperture by a factor of
> 2, then the maximum position point reduces by a factor of 4, as it
> should, but its just 100 x too large.
> 
> I have looked at this in different ways, and it looks to be a genuine
> bug.  It might not have been noticed before as its only evident for
> mrad apertures and small beams.
> 
> Is it possible to take a look at this.  I'm going to make a geometric
> source for now/
> 
> Cheers,
> 
> Howard

**Comment by lucarebuffi** [comment]
Fixed in 1.4.81
