### ISSUE TITLE
Incongruence between SHADOW and XOPPY wiggler outputs

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/ShadowOui#200]
Hello Manuel, 

I'm bugging you with another bug (<- see what I did there?) I think I found. 

I'm currently working for the BEATS project, I have been tasked with the ray tracing. I have noticed that the Wiggler flux and spectral power outputs are different between the corresponding Xoppy and Shadow widgets.  I am using the same parameters for the wiggler, in particular, the same magnetic field map. 

I attach here for your reference: 

1) a zip file containing: the OWS file of my work. and the .dat file containing the magnetic field map
2) a pdf that shows the results of both the widgets, for a quick visual reference. 

I am now wondering whether this is really a bug, or is it more likely that the difference in output is due to the ring parameters included in Shadow, but not in Xoppy? My apologies if the question is silly, and thank you for your help. 

Matteo

[Shadow-Xoppy wiggler incongruence.pdf](https://github.com/oasys-kit/ShadowOui/files/3235614/Shadow-Xoppy.wiggler.incongruence.pdf)

[Archive.zip](https://github.com/oasys-kit/ShadowOui/files/3235611/Archive.zip)

**Comment by srio** [comment]
It looks that the plot setting are different, SHADOW Wiggler is lin/log and XOPPY-Wiggler is log/log. Use the plot's toolbar to switch from lin to log and back.

**Comment by maltissimo** [comment]
Shame on me… sorry for bothering you with these silly things, my apologies.
