### ISSUE TITLE
Crystal with external profile gives bad results for polychromatic source

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#206]
the option of external profile does not produce the desired Z(energy) dispersion . It works only for monochromatic sources. I guess that it calculates the ray reflectivity interpolating in the reflectivity curve for (theta_incident-theta_bragg), but theta_bragg must be calculated for each ray taken into consideration its particular energy.

**Comment by lucarebuffi** [comment]
That was not designed for polichromatic source, since the diffraction profile is for one energy only. It can be changed, but this is not a bug.

**Comment by lucarebuffi** [comment]
Modified in ShadowOui 1.5.45, now it manage the polychromatic.

Input file must be: Th-Th Bragg, Reflectivity
