### ISSUE TITLE
How can I import a self-designed surface?

### ISSUE THREAD

**Issue by LiMiao-GE-ISS** [oasys-kit/ShadowOui#207]
hi，This is a fantastic tool to simulate the diffraction of the benting crystal.   But I still have to ask : how can I import a self-designed surface?  I've generated a corresponding surface.hdf5 file and converted to the Preprocessor data which could be used as input for O.P element.   But it looks like the import surface data was recognized as slope error data

**Comment by lucarebuffi** [comment]
That is exactly what the preprocessor should do. If you import a surface as preprocessor data, it will interpreted as error surface. If you add this "error profile" to a flat mirror, you will see that the new added shape is working instead. I suggest to use a very fine mesh of the added surface.

**Comment by lucarebuffi** [comment]
If you want to add an error profile to your custom surface, you should use the "merge surface" tool and add the error profile to the custom surface, before attaching the result as preprocessor data to the shadow object.

**Comment by LiMiao-GE-ISS** [comment]
> If you want to add an error profile to your custom surface, you should use the "merge surface" tool and add the error profile to the custom surface, before attaching the result as preprocessor data to the shadow object.

Really appreciate your kind reply~   That's exactly what i need to know.  thanks~
