### ISSUE TITLE
crystals should accept surface error file

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#208]
When connecting an error file to a crystal it complains: 

![image](https://user-images.githubusercontent.com/502315/75804144-66a51980-5d34-11ea-8e96-85c3691e3033.png)

We can always set it manually, but I think there is no reason to block it.

**Comment by lucarebuffi** [comment]
I guess that is very old stuff. I agree, there is no reason to block it.

**Comment by lucarebuffi** [comment]
Modified in ShadowOui 1.5.40
