### ISSUE TITLE
crystals in Bragg geometry should not show "thickness"

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#211]
SHADOW always uses thick-crystal-approximation for Bragg geometry. 
Therefore the thickness field should not be shown for Bragg geometry (it should be shown for Laue geometry)

Thanks!

**Comment by lucarebuffi** [comment]
Are you referring to this?

**Comment by lucarebuffi** [comment]
Fixed in 1.5.75

**Comment by srio** [comment]
Thanks. But "Thickness" should appear in Laue (OK), not in Bragg (not OK). 
It must be the same behavior as "Below [-1], onto [1] Bragg planes"

**Comment by lucarebuffi** [comment]
That's exactly what it does...
