### ISSUE TITLE
Flat vs. uniform geometrical source

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui#212]
It seems that "uniform" angular distribution for geometrical source is actually identical to "flat" one, and is not spherical as intended (see figure below). This is visible, however, only at very high angles, maybe not relevant for most calculations.

![image](https://user-images.githubusercontent.com/42113408/85586035-c1a7a700-b66a-11ea-9adc-a82db821839b.png)

**Comment by lucarebuffi** [comment]
This is pre-existing Shadow3 behavior. Please refer to the oasis-kit/shadow3 repository
