### ISSUE TITLE
CRL thickness error

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui#213]
Since a very promising option of considering CRL thickness error appeared in the HYBRID SCREEN widget, are there ways to introduce this error into the CRL or LENS SHADOW widgets?

**Comment by lucarebuffi** [comment]
It's the hybrid screen doing the job, just plug it after a CRL widget. The thickness error reader is in the SYNED Tools.
![Screen Shot 2020-06-28 at 2 32 35 PM](https://user-images.githubusercontent.com/6713598/85956595-6fa5a080-b94c-11ea-9497-e83a2d2f4079.png)

**Comment by lucarebuffi** [comment]
[Be_2D_R50um_D400um_1p778um.txt](https://github.com/oasys-kit/ShadowOui/files/4842908/Be_2D_R50um_D400um_1p778um.txt)

**Comment by lucarebuffi** [comment]
In attachment an example of a real thickness error profile calculated by using measurements taken at the 1BM @ APS. You can use it as input for the Thickness file reader.

**Comment by lucarebuffi** [comment]
The Syned widget works both with ShadowOui-Hybrid and SRW
