### ISSUE TITLE
Unexpected behavior of CRL + crystal

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui#214]
When testing schemes with collimating lens installed before asymmetrically cut crystal, I found an unexpected behavior: lens widgets that use PreRefl data, followed by asymmetrically cut crystal produce a strange diagonal strike in beam cross-section, which I cannot explain physically. In addition, when using the 'ideal lens' widget instead (but with the same focal distance), the resulting beam cross-section is OK (see also .ows with example here: [Test.zip](https://github.com/oasys-kit/ShadowOui/files/4990374/Test.zip)).
![lens and crystal](https://user-images.githubusercontent.com/42113408/88705352-9b799900-d139-11ea-9b52-9f12e83c47bb.png)

**Comment by srio** [comment]
This issue is moved to shadow3:
https://github.com/oasys-kit/shadow3/issues/43
