### ISSUE TITLE
Laue Crystal settings

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/ShadowOui#216]
Ciao Manuel, 

I have something interesting for your attention. I am simulating a beamline, that will want to use a Double Laue Mono, on Si 111. 

There are 2 separate issues, one should be simple, and the other I believe computational. Let me start with the first. 
When you plot the X,Z graph on the widget, the X FWHM is not calculated correctly. I think there is a factor of 2 missing somewhere. I am using a BM source, and taking 10 mrad, so at 13 mt from the source, the FWHM should be somewhere in the range of 13 cm. It's double, so there must be a factor of 2 missing somewhere in the calculations. If I PlotXY the same thing, the FWHM is displayed correctly. See attached images and .ows file. 

![Screen Shot 2020-09-15 at 11 55 35](https://user-images.githubusercontent.com/41440861/93196368-a1a7f100-f74a-11ea-9d3b-108dbbedbb0e.png)
![Screen Shot 2020-09-15 at 11 57 06](https://user-images.githubusercontent.com/41440861/93196377-a40a4b00-f74a-11ea-9449-68722dfecdd2.png)

The other issue revolves around the mosaicity of the crystal. When using a Si crystal, normally it's pretty much a single crystal, so one expects that, if the incoming beam has 0 divergence, the resulting passing band is the Si intrinsic band, i.e. somewhere around 1.4 10e-4. Well, if I put NO in the Mosaic Crystal section, Shadow does not simulate correctly: intensity is 0, Total good rays = total rays. 

If I select YES in the Mosaic crystal option, I am seeing that the calculation is approximately correct if I set "Angle spread FWHM [deg]" around 1.1 10-4. But I have to play with that number, i.e. I have to manually calculate the Energy FWHM, then fiddle with that value until I get a reasonable answer. I would have expected that, if I set the "Angle spread..." to 0, then I would have obtained the correct Energy FWHM, i.e., the Darwin curve. 

I hope I was able to explain myself clearly enough. By all means, please fire back questions if need be. 

Cheers

Matteo

[Laue issues - MA .ows.zip](https://github.com/oasys-kit/ShadowOui/files/5224181/Laue.issues.-.MA.ows.zip)

**Comment by srio** [comment]
1) For the Laue (non mosaic) you should always use asymmetric. If your crystal is symmetric, the asymmetry angle is 90 deg, but there is a bug for this value, so you must put something close, like 89.999. 

With this, and using a monochromatic source, you get the 13cm you expect: 

![image](https://user-images.githubusercontent.com/502315/93200141-b0dd6d80-f74f-11ea-84eb-9857d99177cc.png)


The mosaic crystal result do not converge to perfect crystal for mosaicity zero. You should always use values that are much larger than the Darwin width.  

Does it make sense? 

Updated workspace: 
[Laue issues - MA.zip](https://github.com/oasys-kit/ShadowOui/files/5224287/Laue.issues.-.MA.zip)

**Comment by maltissimo** [comment]
Thank you for the tips!
 I still get the 26cm FHWM though, see attached ( I used the .ows file you uploaded). 

![Screen Shot 2020-09-15 at 12 47 30](https://user-images.githubusercontent.com/41440861/93201711-d9666700-f751-11ea-9389-4e000161614c.png)

Everything else makes sense. Thank you

**Comment by srio** [comment]
That's very weird. Indeed in the plot, you see the width is ~13 cm (from -60000 um to +60000um). And in the plotxy widget attached is also correct. It looks it is a problem of computing or displaying the FWHM. But it works well in other cases... @lucarebuffi : could you have a look?

**Comment by jureyherrera** [comment]
Dear all,
Regarding the display values of FWHM, that happens sometimes when the number of digits is large (including the decimals), but the number is still there, is just a matter of click on it and scroll left with the keyboard arrow, example:

![image](https://user-images.githubusercontent.com/31166917/93342132-426fdc80-f82f-11ea-8ae1-ecab542b0c80.png)

After:
![image](https://user-images.githubusercontent.com/31166917/93342224-603d4180-f82f-11ea-9a32-4b5ff83ba7ed.png)

I hope you find this helpful.

Kind regards,
Juan

**Comment by srio** [comment]
Thanks a lot Juan. Indeed this is our problem which in fact is not a problem. Matteo, of you are satisfied please close the issue!

**Comment by lucarebuffi** [comment]
Just a reminder: if you use PlotXY you can not only leave the units in mm (useful when numbers are big in um), but you can increase the number of bins, in order to have a more precise calculation of FWHM

**Comment by maltissimo** [comment]
Thank you for your help, I'm closing the issue.
