### ISSUE TITLE
CRL: User parameters, attenuation coefficient

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/ShadowOui#217]
Dear Manolo,

I've been trying to configure the ShadowOui CRL widget using a custom refraction index and attenuation coefficients, after some tests, it seems that there is a slightly problem with the units of the Attenuation coefficient, when the units in the scheme are not **_cm_** : 

For example, for a **25.25 keV** beam:

- This is using a **Be** Prerefl file.

![image](https://user-images.githubusercontent.com/31166917/93619228-8e11ba00-f9d8-11ea-9576-a4bf00c40dff.png)
![image](https://user-images.githubusercontent.com/31166917/93619446-d4ffaf80-f9d8-11ea-8d45-6c57583bf153.png)

- Everything exactly the same but using the refraction index and attenuation coefficient (Be) for this energy:

![image](https://user-images.githubusercontent.com/31166917/93619813-653df480-f9d9-11ea-8ec7-d35a8b435264.png)
![image](https://user-images.githubusercontent.com/31166917/93619584-0e381f80-f9d9-11ea-9bd2-e630fb672667.png)

Where the attenuation coefficient is actually in **_cm^-1_**

Thank you for your attention.

Kind regards,
Juan

**Comment by lucarebuffi** [comment]
yes it is cm-1. Just a wrong label.

Best, Luca

**Comment by lucarebuffi** [comment]
fixed in ShadowOui 1.5.91
