### ISSUE TITLE
"Ray tracing management" in "XRD capillary" widget

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui#218]
/Question/
Could anyone please clarify meaning of "Ray tracing management" parameters ("degrees around peak" and "beam energy") in "XRD capillary" widget? How the required "beam energy" corresponds to energy of individual rays? The original article about the "XRD capillary" widget (JSR 24, 622-635, 2017) does not refer to such parameters.

**Comment by lucarebuffi** [comment]
Degrees around peak: [-degrees around peek + Bragg angle, +degrees around peak + Bragg angle] range around the Bragg angle to be simulated. It optimize the duration of the simulation, by avoiding regions where there is no signal

Beam energy: monochromatic energy of the beam as defined by the monochromator (you need it to perform a XRD experiment)

**Comment by lucarebuffi** [comment]
The article won't mention parameters like those ones, since they are merely operational and don't fit into the physical models description.

**Comment by SergeyRa** [comment]
Thanks a lot!
Does the use of fixed beam energy means that small differences between energy of individual rays (i.e. one wants to model vertical energy gradient introduced by monochromator) are ignored?

**Comment by SergeyRa** [comment]
Or maybe the "beam energy" is "central" energy used only to calculate centers of peak ranges mentioned in your comment above?

**Comment by lucarebuffi** [comment]
The energy to where the beamline is setup (what you call central) is needed in several place here and there in the algorithm, for example to determine how many reflections are present in the angular range where the simulation must be performed. 
It is sometimes used to speed up the calculations when no big dependency on the little bandwidth is expected: the Debye-waller factor, for example, is calculated on the angle and the central energy.
Apart from that every ray is treated individually: the angle of deflection is calculated according to its particular energy (as you can read in the paper). 

Please feel free to dig into the code:

https://github.com/oasys-kit/ShadowOui/blob/master/orangecontrib/shadow/widgets/experimental_elements/ow_xrd_capillary.py

**Comment by SergeyRa** [comment]
Thanks a lot!
