### ISSUE TITLE
Rays distribution in 'XRD capillary'

### ISSUE THREAD

**Issue by SergeyRa** [oasys-kit/ShadowOui#219]
After trying to simulate XRD at 2D detector, I found an unexpected behaviour of 'XRD capillary' widget. When number of rays in the XRPD arc is set to 1, the expected uniform azimutal distribution is generated (note that Lorentz polarization factor is switched off for clarity):
![1 ray in arc](https://user-images.githubusercontent.com/42113408/99909520-aaeda500-2d1b-11eb-8767-c6f578a9fc40.png)
However, when the number of rays in the XRPD arc is set to be >1, one can see an anomalous concentration of diffracted rays (note again that Lorentz polarization factor is switched off):
![10 rays in arc](https://user-images.githubusercontent.com/42113408/99909521-ac1ed200-2d1b-11eb-9d3c-02356e2fd82c.png)
[CAPILLARY.zip](https://github.com/oasys-kit/ShadowOui/files/5579831/CAPILLARY.zip)

**Comment by lucarebuffi** [comment]
fixed in 1.5.104

**Comment by lucarebuffi** [comment]
A note on your example: the empty element, to work properly in the way you intended for, must have incident angle 0 and reflection angle 180.

I also modified the example to show you an alternative and more realistic simple case.
[CAPILLARY.ows.zip](https://github.com/oasys-kit/ShadowOui/files/5584901/CAPILLARY.ows.zip)

**Comment by SergeyRa** [comment]
Many thanks!

**Comment by lucarebuffi** [comment]
You are the first known user of this widget, so you have a special treatment!
