### ISSUE TITLE
upgrade failed: ShadowOuiAdvancedTools 1.0.57 < 1.0.60

### ISSUE THREAD

**Issue by antmobilogy** [oasys-kit/ShadowOui#220]
I have encountered error while doing an update for  ShadowOuiAdvancedTools 1.0.57 on Windows10.  Please assist.
==>
from C:\Users\xxx\AppData\Local\Temp\pip-uninstall-ys84cxhy\sip.pyi
Moving to c:\users\xxx\appdata\roaming\python\python37\site-packages\pyqt5\uic\
from c:\users\xxx\appdata\roaming\python\python37\site-packages\pyqt5\~ic
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\xxx\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyQt5\\Qt\\bin\\Qt5Bluetooth.dll'
Check the permissions.
==>
![image](https://user-images.githubusercontent.com/9425741/109479243-25fdee80-7ab5-11eb-9bf1-ed19ee32e11f.png)

**Comment by srio** [comment]
Did you install OASYS following the instructions? Your messages show that it is doesn't look for the right directories.  Do you have the directory C:\users\xxx\miniconda3? If so try the following in a cmd window:
```
c:\users\xxx\miniconda3\Scripts\activate
pip install --upgrade OASYS1-ShadowOui-Advanced-Tools
```

**Comment by antmobilogy** [comment]
Hi Srio, 

Thanks for your speedy reply. I have input the command given by you but it didn't work.

See below message:

C:\Users\xxx\Miniconda3\Scripts>activate  pip install --upgrade OASYS1-ShadowOui-Advanced-Tools
activate does not accept more than one argument:
['pip', 'install', '--upgrade', 'OASYS1-ShadowOui-Advanced-Tools']

**Comment by srio** [comment]
There are two commands. Enter one after the other.

**Comment by antmobilogy** [comment]
Hi Srio,

The commands work like a charm. Thank you!


Successfully built OASYS1-ShadowOui-Advanced-Tools
Installing collected packages: PyQt5, OASYS1-ShadowOui-Advanced-Tools
  Attempting uninstall: PyQt5
    Found existing installation: pyqt5 5.15.3
    Uninstalling pyqt5-5.15.3:
      Successfully uninstalled pyqt5-5.15.3
  Attempting uninstall: OASYS1-ShadowOui-Advanced-Tools
    Found existing installation: OASYS1-ShadowOui-Advanced-Tools 1.0.57
    Uninstalling OASYS1-ShadowOui-Advanced-Tools-1.0.57:
      Successfully uninstalled OASYS1-ShadowOui-Advanced-Tools-1.0.57
Successfully installed OASYS1-ShadowOui-Advanced-Tools-1.0.60 PyQt5-5.15.2

**Comment by srio** [comment]
Great!
Enjoy Oasys!
