### ISSUE TITLE
Not calculating intensities with high rays count

### ISSUE THREAD

**Issue by maltissimo** [oasys-kit/ShadowOui#224]
Hello, 

while checking the differences in Shadow-calculated intensities from a Bragg and a Laue DCM, we discovered that by selecting the Laue diffraction, if the number of rays exceeds 1 million, then the resulting intensity is computed as Nan (see attached .ows file and screenshots), i.e. 
Shadow computes the intensity for 1 million rays, but doesn't for say 2 millions or more. 
This is troublesome when trying to improve statistics. 

Happy to help anyway I can. 

ciao

Matteo

[Mrays_bug.zip](https://github.com/oasys-kit/ShadowOui/files/7202211/Mrays_bug.zip)

**Comment by lucarebuffi** [comment]
The problem is most probably in shadow3. Make a cumulating loop and you avoid the problem.

**Comment by lucarebuffi** [comment]
Anyway, if only 1 ray, for some reason, gives a NaN intensity on its own, the entire intensity of the beam will be NaN.
This is most likely happening with a big number of rays. I really don't believe is related with the exact number of rays, in fact, by changing the seed of the source the problem disappear.

![Screen Shot 2021-09-21 at 2 22 20 PM](https://user-images.githubusercontent.com/6713598/134234411-abc8ab30-1233-4bcd-8bc3-42916a100c84.png)
