### ISSUE TITLE
The positioning angle of the hyperbolic mirror is invalid

### ISSUE THREAD

**Issue by Jack560440** [oasys-kit/ShadowOui#236]
An elliptical mirror can be defined by the major axis and the minor axis, and the angle of MajAx and pole is used to determine the position of the reflection. For hyperbolic mirrors, is this also the angle between the MajAx and pole as shown in picture? And this angle has no effect on the output when the surface is a hyperbolic mirror.
![picture1](https://user-images.githubusercontent.com/127837007/225006815-0e62d776-3aca-4494-857a-8ae2288b5f31.png)

**Comment by srio** [comment]
The calculation of the hyperbola parameters either from the internal parameters (p,q,theta) or the external ones (p, delta) is buggy in shadow3. 

If you need to simulate hyperbolas, I suggest that you calculate the conic coefficients and use the corresponding widget. 

To calculate the conic coefficients, you can see our very recent paper: https://doi.org/10.1107/S1600577523001492

HTH!

**Comment by Jack560440** [comment]
Thank you for your prompt reply.  It is very helpful to me.
