### ISSUE TITLE
footprint reader tool 

### ISSUE THREAD

**Issue by Jae-yong-Shin** [oasys-kit/ShadowOui#237]
Hello,
I'm trying to utilize the 'footprint reader' as shown in the picture below, but there is no tool that can be connected to the input (Python script is connected). I wonder if the installation is incorrect. All other shadows are functioning properly.
![image](https://github.com/oasys-kit/oasys-installation-scripts/assets/145250428/a04e0b32-3e23-45ad-bc2d-f3d5c4cf1c2c)

**Comment by lucarebuffi** [comment]
Installation is correct, you are using the widget improperly.

The footprint reader is for thermal load calculations only (an advanced features), it won't work in the way you are trying to use it. Said that, to extract the footprint as a beam and be able to display it, you must active the emission of the footprint in the preferences.

![Screenshot 2023-10-06 at 10 05 33 AM](https://github.com/oasys-kit/ShadowOui/assets/6713598/e8e3a1f7-b1e3-4ed9-bfc1-109f9514c30c)

When that is active, optical elements will emit both the usual beam, and their footprint as an additional signal.

**Comment by Jae-yong-Shin** [comment]
Thank you for kindly answering my question. I appreciate it. I confirmed that it works correctly in the linux(ubuntu OS) after changing the options as you explained. However, it still doesn't work in the Windows 11 OS. Could it be an issue with Windows 11?
