### ISSUE TITLE
Foot print reader is not working in window os

### ISSUE THREAD

**Issue by Jae-yong-Shin** [oasys-kit/ShadowOui#238]
Hello,
I changed the options as advised in issue #237, and confirmed that it is working correctly on Linux OS. However, on Windows OS (Windows 10, 11), the footprint reader still doesn't work even after changing the options. Can you identify what the problem might be? If you need any information to diagnose the issue, I will provide it immediately.

![image](https://github.com/oasys-kit/ShadowOui/assets/145250428/fb8c1589-0ce3-4956-a9fc-a19e9248d57f)
![image](https://github.com/oasys-kit/ShadowOui/assets/145250428/ccec7f1a-32d0-40c1-8b92-5a1cc330e545)
![image](https://github.com/oasys-kit/ShadowOui/assets/145250428/af290cdf-bc8b-4901-8f79-bdce0a0ac831)

**Comment by lucarebuffi** [comment]
Windows will never end to surprise me for its horrible relationship with Python.
There is no bug whatsoever, but for some mysterious reason the correct signal setup appears if I add one nonsense line of code to the constructor of the involved widget....

from OpticalElement constructor:

    def __init__(self):
        graphical_Options=ow_optical_element.GraphicalOptions(is_mirror=True)

        super().__init__(graphical_Options)

        gui.rubber(self.controlArea)

        gui.rubber(self.mainArea)

        **_print(self.outputs)_**

From PlotXY widget constructor:

    def __init__(self):
        super().__init__()
	
        **_print(self.inputs)_**

That printout, solve the problem. I find out while quickly debugging on a windows system. I will prepare a better workaround, but it's complete nonsense.

**Comment by lucarebuffi** [comment]
![Screenshot 2023-10-09 at 11 50 52 AM](https://github.com/oasys-kit/ShadowOui/assets/6713598/57ec51ed-15c3-4266-89e1-614086cabad1)

**Comment by lucarebuffi** [comment]
Please update ShadowOui as soon as a new version will be available.

**Comment by Jae-yong-Shin** [comment]
Thank you for your prompt reply. After the update, the problem is solved.
