### ISSUE TITLE
Off axis paraboloidal mirror + mirror dimensions

### ISSUE THREAD

**Issue by Johirul5** [oasys-kit/ShadowOui#239]
Is it possible to create an off axis paraboloidal mirror in shadowoui? Like this:
![OAP_Mirror_Obtuse_Angle_A2-780](https://github.com/oasys-kit/ShadowOui/assets/136444612/028c846e-df22-4796-aa81-c4b2183993a1)

I know i can create something similar with the paraboloidal mirror object by restricting the dimensions but i think the mirror always starts from the origin:
![image](https://github.com/oasys-kit/ShadowOui/assets/136444612/acc85efa-2fdf-40f9-b0a5-c36b0c7b0f5a)
![image](https://github.com/oasys-kit/ShadowOui/assets/136444612/534d0bea-cc53-46e1-929a-e485ffee92aa)

One way to possibly to do this may be
To adjust he mirror dimensions feature so it is possible to create a mirror that doesn't need to start from the origin. I could also see a benefit in other optics widgets (mirrors/crystals widgets). 

Thank you,
Jo

**Comment by lucarebuffi** [comment]
You should use the tab Advanced Settings -> O.E. movements and displace the mirror relatively to its ideal position (in-axis). 
This is the right way to do it.

**Comment by Johirul5** [comment]
> You should use the tab Advanced Settings -> O.E. movements and displace the mirror relatively to its ideal position (in-axis). This is the right way to do it.

Thanks, 
I may have not explained well what an off-axis parabolic mirror since the name is a little bit deceiving. 
"An off-axis parabolic (OAP) mirror consists of a small section cut out from a larger, so-called “parent” parabolic mirror."  like this:
![image](https://github.com/oasys-kit/ShadowOui/assets/136444612/63a4c20a-8408-44c1-a925-d76069eb150d)

So just moving the mirror relative to its ideal position would not simulate this since the shape of the mirror would need to change according to the shape of the parabola at that point. 

Does this make more sense?

**Comment by lucarebuffi** [comment]
In this case, the best thing is to overlap an obstruction (at 0 distance) (Screen/Slits).
