### ISSUE TITLE
Problem creating polynomial surfaces in ShadowOUI

### ISSUE THREAD

**Issue by yangyang-fdu** [oasys-kit/ShadowOui#242]
Could not find the polynomial option when create any optical element in ShadowOUI, which can be found in ShadowVUI。
Is there any other way to create such surfaces, such as 3rd order polynomial surfaces, in ShadowOUI?
Thanks in advance!

**Comment by yangyang-fdu** [comment]
Thank you so much for the quick reply~ I tried using use the Conic Coefficients Crystal widget, but the parameters in basic setting  for the surface shape are c[1]-c[10], which represent c[1]X^2+c[2]Y^2+c[3]Z^2+c[4]XY+c[5]YZ+....+c[9]Z+c[10], if my understanding is correct. it seems not possible to build a surface with X^3 term or Y^3 term from this function. Did I miss any thing?

**Comment by srio** [comment]
No, the conic coefficients are for a quadratic surface (order 2). If you want another surface you have to create a file with a mesh z(x,y) and use the option external surface/spline over a flat mirror. See the example 21 of the tutorial: https://github.com/oasys-kit/shadowOui-tutorial
