### ISSUE TITLE
Add-on mechanism not working behind ESRF proxy

### ISSUE THREAD

**Issue by lucarebuffi** [oasys-kit/ShadowOui#37]
Pip is not working behind ESRF proxy even if the environmental variables:

```
https_proxy="http://\<proxy.server\>:\<port\>"
http_proxy="http://\<proxy.server\>:\<port\>"
```

are set.

**Comment by srio** [comment]
Yes. We do know. 
Two bad solutions (by now): 
-Try to open a root shell with the proxy parameters defined and restart oasys
-Install manually ShadowOui: 
      i) git clone...
     ii) python3 setup.py sdist develop

**Comment by srio** [comment]
This is not longer an issue. It works now, don't ask why.
