### ISSUE TITLE
Beamline Viewer

### ISSUE THREAD

**Issue by lucarebuffi** [oasys-kit/ShadowOui#62]

**Comment by lucarebuffi** [comment]
http://zulko.github.io/blog/2014/11/13/things-you-can-do-with-python-and-pov-ray/

**Comment by srio** [comment]
Just for info (although I do not like it) the Danish guys of McStas developed a web platform 
https://www.e-neutrons.org/ssp/
with a 3D viewer based on 
http://www.instantreality.org/story/what-is-it/

It loos like:

![image](https://cloud.githubusercontent.com/assets/502315/13522476/2689ac6c-e1f0-11e5-906e-2f46fb09e37c.png)

**Comment by lucarebuffi** [comment]
IT'S DONE! See ShadowOui 1.5.145, for the first working prototype using Matplotlib and some magic
