### ISSUE TITLE
Idea for enhancement: absolute histogram scale (photons or power)

### ISSUE THREAD

**Issue by srio** [oasys-kit/ShadowOui#97]
Something that could improve the performances of shadow is to "calibrate" automatically histograms where the scale is directly number of photons or power. This could be done if the source spectrum is calculated at the source and the information carried out with it. Or just assigning a "number of photons" to each ray. We must think about that... I'm just writing it for not forgetting...

**Comment by lucarebuffi** [comment]
Just a note: I compared wiggler spectrum from shadow with the results of SPECTRA software and they are in good agreement.

**Comment by lucarebuffi** [comment]
Done for undulatory sources
